### ISSUE TITLE
Error in hazelcast-kubernetes v1.5.1 

### ISSUE THREAD

**Issue by enozcan** [hazelcast-guides/caching-springboot-microservices-on-kubernetes#9]
edit: v1.4 & 1.4.1 has the same error as well.

Works properly in 1.3.1 (for both hazelcast 3.11.2 and 3.12.1). In 1.5.1, the failure raises:

```
java.lang.IllegalStateException: Unknown protocol: HTT
        at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107) ~[hazelcast-3.12.1.jar!/:3.12.1]
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135) ~[hazelcast-3.12.1.jar!/:3.12.1]
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369) [hazelcast-3.12.1.jar!/:3.12.1]
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354) [hazelcast-3.12.1.jar!/:3.12.1]
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280) [hazelcast-3.12.1.jar!/:3.12.1]
        at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235) [hazelcast-3.12.1.jar!/:3.12.1]
```

**Comment by enozcan** [comment]
Adding 5701 containerPort for statefulSet solved the problem.
